# Generated by Django 3.2 on 2021-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
